sudo: false
language: node_js
node_js:
  - "0.12"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gulp webdriver &
  - sleep 2
script:
  - gulp
notifications:
  email: false
