sudo: false
language: node_js
node_js:
  - "0.12"
before_script:
  - nohup bash -c "./node_modules/.bin/webdriver-manager start 2>&1 &"
  - sleep 2
script:
  - ./node_modules/.bin/protractor protractor.conf.js
notifications:
  email: false
cache:
  directories:
    - node_modules
