sudo: false
language: node_js
node_js:
  - "0.12"
install:
  - npm install
  # use firefox on travis
  - node_modules/.bin/webdriver-manager update --standalone --firefox
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "./node_modules/.bin/webdriver-manager start 2>&1 &"
  - sleep 2
script:
  - ./node_modules/.bin/protractor protractor.conf.js
notifications:
  email: false
cache:
  directories:
    - node_modules
